# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Demo.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 827)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 90, 1041, 671))
        self.tabWidget.setObjectName("tabWidget")
        self.rawtab = QtWidgets.QWidget()
        self.rawtab.setObjectName("rawtab")
        self.gridLayout = QtWidgets.QGridLayout(self.rawtab)
        self.gridLayout.setObjectName("gridLayout")
        self.rawimgshow = QtWidgets.QGraphicsView(self.rawtab)
        self.rawimgshow.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rawimgshow.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rawimgshow.setObjectName("rawimgshow")
        self.gridLayout.addWidget(self.rawimgshow, 0, 0, 1, 1)
        self.tabWidget.addTab(self.rawtab, "")
        self.odtab = QtWidgets.QWidget()
        self.odtab.setObjectName("odtab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.odtab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.odimgshow = QtWidgets.QGraphicsView(self.odtab)
        self.odimgshow.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.odimgshow.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.odimgshow.setObjectName("odimgshow")
        self.gridLayout_2.addWidget(self.odimgshow, 1, 0, 1, 1)
        self.ganimgshow = QtWidgets.QGraphicsView(self.odtab)
        self.ganimgshow.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ganimgshow.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ganimgshow.setObjectName("ganimgshow")
        self.gridLayout_2.addWidget(self.ganimgshow, 1, 1, 1, 1)
        self.tabWidget.addTab(self.odtab, "")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 50, 461, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.loadbutton = QtWidgets.QPushButton(self.widget)
        self.loadbutton.setObjectName("loadbutton")
        self.horizontalLayout.addWidget(self.loadbutton)
        self.openbutton = QtWidgets.QPushButton(self.widget)
        self.openbutton.setObjectName("openbutton")
        self.horizontalLayout.addWidget(self.openbutton)
        self.clearbutton = QtWidgets.QPushButton(self.widget)
        self.clearbutton.setObjectName("clearbutton")
        self.horizontalLayout.addWidget(self.clearbutton)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(560, 50, 216, 25))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.stylechoose = QtWidgets.QComboBox(self.widget1)
        self.stylechoose.setObjectName("stylechoose")
        self.stylechoose.addItem("")
        self.stylechoose.addItem("")
        self.stylechoose.addItem("")
        self.stylechoose.addItem("")
        self.horizontalLayout_2.addWidget(self.stylechoose)
        self.tranbutton = QtWidgets.QPushButton(self.widget1)
        self.tranbutton.setObjectName("tranbutton")
        self.horizontalLayout_2.addWidget(self.tranbutton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1104, 23))
        self.menubar.setObjectName("menubar")
        self.menuMask_RCNN_Cartoon_GAn = QtWidgets.QMenu(self.menubar)
        self.menuMask_RCNN_Cartoon_GAn.setObjectName("menuMask_RCNN_Cartoon_GAn")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMask_RCNN_Cartoon_GAn.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.clearbutton.clicked.connect(self.lineEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Demo_odg"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rawtab), _translate("MainWindow", "初始图像"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.odtab), _translate("MainWindow", "对象检测及变换后图像"))
        self.loadbutton.setText(_translate("MainWindow", "浏览"))
        self.openbutton.setText(_translate("MainWindow", "读取图像"))
        self.clearbutton.setText(_translate("MainWindow", "清空路径"))
        self.label.setText(_translate("MainWindow", "风格选择："))
        self.stylechoose.setItemText(0, _translate("MainWindow", "宫崎骏"))
        self.stylechoose.setItemText(1, _translate("MainWindow", "细田守"))
        self.stylechoose.setItemText(2, _translate("MainWindow", "今敏"))
        self.stylechoose.setItemText(3, _translate("MainWindow", "新海诚"))
        self.tranbutton.setText(_translate("MainWindow", "开始检测变换"))
        self.menuMask_RCNN_Cartoon_GAn.setTitle(_translate("MainWindow", "Mask RCNN & Cartoon GAn"))

